apiVersion: v1
kind: Service
metadata:
  name: dns-manager
  namespace: dns-manager
  labels:
    app.kubernetes.io/name: dns-manager
spec:
  type: ClusterIP
  selector:
    app.kubernetes.io/name: dns-manager
    app.kubernetes.io/component: web
  ports:
    - name: http
      port: 80
      targetPort: http
